name: 🔄 Update YouTube Video Lists

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 06:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-videos:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: npm install axios

      - name: 📡 Fetch Channel & Playlist Videos
        run: |
          node <<EOF
          const axios = require('axios');
          const fs = require('fs');

          const apiKey = 'YOUR_API_KEY';
          const channelId = 'UC2B97jlqSitLg21CTBAnBFQ';
          const playlistId = 'PLIfNU8e0FSYcfymK5sYQfJVr_x4qlYNyJ';

          async function fetchChannelVideos() {
            const url = `https://www.googleapis.com/youtube/v3/search?key=${apiKey}&channelId=${channelId}&part=snippet,id&order=date&maxResults=10`;
            const res = await axios.get(url);
            const videos = res.data.items.map(item => ({
              title: item.snippet.title,
              id: item.id.videoId
            }));
            fs.writeFileSync('channel-videos.json', JSON.stringify(videos, null, 2));
          }

          async function fetchPlaylistVideos() {
            const url = `https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=50&playlistId=${playlistId}&key=${apiKey}`;
            const res = await axios.get(url);
            const videos = res.data.items.map(item => ({
              title: item.snippet.title,
              id: item.snippet.resourceId.videoId
            }));
            fs.writeFileSync('playlist-videos.json', JSON.stringify(videos, null, 2));
          }

          fetchChannelVideos();
          fetchPlaylistVideos();
          EOF

      - name: 📤 Commit updated JSON files
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add *.json
          git commit -m "🚀 Update video lists"
          git push
